public enum ReagentName{
	SimpleRed = 0,
	SimpleBlue = 1,
	SimpleYellow = 2,
	SimpleGreen = 3,
	SimpleBlack = 4,
	SimpleBrown = 5,
	SimpleGrey = 6,
	SimpleOrange = 7,
	SimplePurple = 8,
	SimpleFire = 9,
	SimpleWhite = 10,
	SimplePink = 11,
	SimpleOlive = 12,
	SimpleTeal = 13,
	SimpleCoral = 14,
	SimpleCyan = 15,

	PotionLove = 16,
	PotionPower = 17,
	PotionLoyalty = 18,
	PotionKnowledge = 19,
	PotionFire = 20,
	PotionInvisible = 21,
	PotionEternity = 22,
	PotionOblivion = 23,
	PotionDominion = 24,
	PotionLastSleep = 25,
	PotionProtection = 26,
	PotionSecretVision = 27,
	PotionPolyglotum = 28,
	PotionCensure = 29,
	PotionIsidasMortum = 30,
	PotionYouth = 31,

	ElixirTelepathy = 32,
	ElixirWisdom = 33,
	ElixirLordPlants = 34,
	ElixirFlight = 35,

	AmuletTeleportation = 36,
	AmuletMasterOfBeasts = 37,
	AmuletBlood = 38,
	AmuletSecretVision = 39,

	Unicorn = 40,
	Griffin  = 41,
	Basilisk = 42,
	Medusa  = 43,

	PowderControl = 44,
	PowderIncorporeal = 45,
	PowderTruth = 46,
	PowderFate = 47,

	GreatElixirPower = 48,
	GreatElixirEpiphany = 49,
	GreatElixirRevival = 50,
	GreatElixirOmen = 51,
	GreatElixirDisappearance = 52,
	GreatElixirTime = 53,
	GreatElixirProtection = 54,
	GreatElixirEternalLove = 55,

	Guard  = 56,
	Salamander = 57,
	Dragon = 58,
	Banshee = 59,

	UltraGreatElxir = 60,
	UltraGreatAmulet = 61,

	GetUpCardFromCloset = 80,
	SwapCardInSubject = 81,
	SwapCardClosetAndSubject = 82
}